name: static check
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: grandcolline/golang-github-actions@v1.0.0
        with:
          run: fmt
          token: ${{ secrets.GITHUB_TOKEN }}
