# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go fmt ./...
      - run: |
          if [ -n "$(git diff --exit-code)" ]; then
            echo "Code was not formatted with go fmt"
            exit 1
          fi
